FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY data ./data
COPY eval ./eval
COPY docker/entrypoint_api.sh ./entrypoint_api.sh
RUN chmod +x ./entrypoint_api.sh

EXPOSE 8000

ENTRYPOINT ["./entrypoint_api.sh"]
